{
 "title": "ECS Prometheus Data",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Requests Distribution Among Nodes",
   "type": "piechart",
   "description": "Total number of HTTP requests handled",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/ecs/containerinsights/friends-capstone-cluster/prometheus:*",
       "name": "/aws/ecs/containerinsights/friends-capstone-cluster/prometheus"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/ecs/containerinsights/friends-capstone-cluster/performance:*",
       "name": "/aws/ecs/containerinsights/friends-capstone-cluster/performance"
      }
     ],
     "metricName": "flask_http_request_total",
     "namespace": "ECS/ContainerInsights/Prometheus",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Total HTTP Requests Handled",
   "type": "timeseries",
   "description": "Total number of HTTP requests",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "dimensions": {
      "ClusterName": "friends-capstone-cluster",
      "TaskDefinitionFamily": "friends-capstone-crud-api-ecs-task"
     },
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/ecs/containerinsights/friends-capstone-cluster/performance:*",
       "name": "/aws/ecs/containerinsights/friends-capstone-cluster/performance"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/ecs/containerinsights/friends-capstone-cluster/prometheus:*",
       "name": "/aws/ecs/containerinsights/friends-capstone-cluster/prometheus"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/ecs-cwagent-prometheus:*",
       "name": "/ecs/ecs-cwagent-prometheus"
      }
     ],
     "metricName": "flask_http_request_total",
     "namespace": "ECS/ContainerInsights/Prometheus",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Total HTTP Request Exceptions",
   "type": "stat",
   "description": "Total number of HTTP requests which resulted in an exception",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/ecs/containerinsights/friends-capstone-cluster/performance:*",
       "name": "/aws/ecs/containerinsights/friends-capstone-cluster/performance"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/ecs/containerinsights/friends-capstone-cluster/prometheus:*",
       "name": "/aws/ecs/containerinsights/friends-capstone-cluster/prometheus"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/ecs-cwagent-prometheus:*",
       "name": "/ecs/ecs-cwagent-prometheus"
      }
     ],
     "metricName": "flask_http_request_exceptions_total",
     "namespace": "ECS/ContainerInsights/Prometheus",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Process CPU Seconds",
   "type": "timeseries",
   "description": "Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "dimensions": {
      "ClusterName": "friends-capstone-cluster",
      "TaskDefinitionFamily": "friends-capstone-crud-api-ecs-task"
     },
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/ecs/containerinsights/friends-capstone-cluster/performance:*",
       "name": "/aws/ecs/containerinsights/friends-capstone-cluster/performance"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/ecs/containerinsights/friends-capstone-cluster/prometheus:*",
       "name": "/aws/ecs/containerinsights/friends-capstone-cluster/prometheus"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/ecs-cwagent-prometheus:*",
       "name": "/ecs/ecs-cwagent-prometheus"
      }
     ],
     "metricName": "process_cpu_seconds_total",
     "namespace": "ECS/ContainerInsights/Prometheus",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  }
 ]
}