{
 "title": "Summary",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Management", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Breakdown of Visitors by Countries",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "Country": "*",
      "WebACL": "friends-capstone-regional-web-acl"
     },
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricName": "AllowedRequests",
     "namespace": "AWS/WAFV2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Breakdown of Visitors by Devices",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "Device": "*",
      "WebACL": "friends-capstone-regional-web-acl"
     },
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricName": "AllowedRequests",
     "namespace": "AWS/WAFV2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Number of New Images Uploaded Per Day",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 1 },
   "targets": [
    {
     "dimensions": {
      "ApiName": "friends-capstone-infra-s3-images-api-gateway",
      "Stage": "dev"
     },
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricName": "Count",
     "namespace": "AWS/ApiGateway",
     "period": "1d",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Number of Cards Already Sent",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "friends-capstone-notification-lambda",
      "Resource": "friends-capstone-notification-lambda"
     },
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-east-1:255945442255:log-group:/aws/lambda/friends-capstone-notification-lambda:*",
       "name": "/aws/lambda/friends-capstone-notification-lambda"
      }
     ],
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "period": "1d",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Number of Cards To Be Sent",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 4, "x": 19, "y": 1 },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "friends-capstone-notification-lambda"
     },
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-east-1:255945442255:log-group:/aws/lambda/friends-capstone-notification-lambda:*",
       "name": "/aws/lambda/friends-capstone-notification-lambda"
      }
     ],
     "metricName": "ProvisionedConcurrencyInvocations",
     "namespace": "AWS/Lambda",
     "period": "1d",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "WAF - Allowed vs Blocked Requests on ALB & APIGW",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "Rule": "ALL",
      "WebACL": "friends-capstone-regional-web-acl"
     },
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricName": "AllowedRequests",
     "namespace": "AWS/WAFV2",
     "period": "2d",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/WAFV2", "type": "string" }, "type": "property" },
      "select": { "name": "AVG", "type": "function" }
     },
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "Rule": "ALL",
      "WebACL": "friends-capstone-regional-web-acl"
     },
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricName": "BlockedRequests",
     "namespace": "AWS/WAFV2",
     "period": "2d",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "WAF - Bot Vs Non-Bot Visitors",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "SUM(SEARCH('AWS/WAFV2 MetricName=(\"SampleBlockedRequest\" OR \"SampleAllowedRequest\" OR \"SampleCaptchaRequest\" OR \"SampleChallengeRequest\") BotCategory=\"ALL_BOTS\" Region=\"us-west-2\" WebACL=\"friends-capstone-regional-web-acl\" VerificationStatus=\"bot:verified\" :aws.AccountId=LOCAL', 'Sum', 3600))",
     "id": "botsverified",
     "label": "Bots:Verified",
     "metricEditorMode": 1,
     "namespace": "AWS/WAFV2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expression": "SUM(SEARCH('AWS/WAFV2 MetricName=(\"SampleBlockedRequest\" OR \"SampleAllowedRequest\" OR \"SampleCaptchaRequest\" OR \"SampleChallengeRequest\") BotCategory=\"ALL_BOTS\" Region=\"us-west-2\" WebACL=\"friends-capstone-regional-web-acl\" VerificationStatus=\"bot:developer_platform:verified\" :aws.AccountId=LOCAL', 'Sum', 3600))",
     "id": "botsdeveloperplatformverified",
     "label": "Bots:DeveloperPlatform",
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expression": "SUM(SEARCH('AWS/WAFV2 MetricName=(\"SampleBlockedRequest\" OR \"SampleAllowedRequest\" OR \"SampleCaptchaRequest\" OR \"SampleChallengeRequest\") BotCategory=\"ALL_BOTS\" Region=\"us-west-2\" WebACL=\"friends-capstone-regional-web-acl\" VerificationStatus=\"bot:user_triggered:verified\" :aws.AccountId=LOCAL', 'Sum', 3600))",
     "id": "botsusertriggeredverified",
     "label": "Bots:UserTriggered:Verified",
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expression": "SUM(SEARCH('AWS/WAFV2 MetricName=(\"SampleBlockedRequest\" OR \"SampleAllowedRequest\" OR \"SampleCaptchaRequest\" OR \"SampleChallengeRequest\") BotCategory=\"ALL_BOTS\" Region=\"us-west-2\" WebACL=\"friends-capstone-regional-web-acl\" VerificationStatus=\"bot:unverified\" :aws.AccountId=LOCAL', 'Sum', 3600))",
     "id": "botsunverified",
     "label": "Bots:Unverified",
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expression": "SUM(SEARCH('AWS/WAFV2 MetricName=(\"SampleBlockedRequest\" OR \"SampleAllowedRequest\" OR \"SampleCaptchaRequest\" OR \"SampleChallengeRequest\") BotCategory=\"NON_BOT\" Region=\"us-west-2\" WebACL=\"friends-capstone-regional-web-acl\" :aws.AccountId=LOCAL', 'Sum', 3600))",
     "id": "nonbots",
     "label": "Non-bots",
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "WAF - Source of Bots Detected",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expression": "SUM(SEARCH('{AWS/WAFV2,Signal,Region,WebACL} MetricName=(\"SampleBlockedRequest\" OR \"SampleAllowedRequest\" OR \"SampleCaptchaRequest\" OR \"SampleChallengeRequest\") Region=\"us-west-2\" WebACL=\"friends-capstone-regional-web-acl\" Signal=\"non_browser_user_agent\" :aws.AccountId=LOCAL', 'Sum', 3600))",
     "id": "nonBrowserUserAgent",
     "label": "NonBrowserUserAgent",
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expression": "SUM(SEARCH('{AWS/WAFV2,Signal,Region,WebACL} MetricName=(\"SampleBlockedRequest\" OR \"SampleAllowedRequest\" OR \"SampleCaptchaRequest\" OR \"SampleChallengeRequest\") Region=\"us-west-2\" WebACL=\"friends-capstone-regional-web-acl\" Signal=\"known_bot_data_center\" :aws.AccountId=LOCAL', 'Sum', 3600))",
     "id": "knownBotDataCenter",
     "label": "KnownBotDataCenter",
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expression": "SUM(SEARCH('{AWS/WAFV2,Signal,Region,WebACL} MetricName=(\"SampleBlockedRequest\" OR \"SampleAllowedRequest\" OR \"SampleCaptchaRequest\" OR \"SampleChallengeRequest\") Region=\"us-west-2\" WebACL=\"friends-capstone-regional-web-acl\" Signal=\"automated_browser\" :aws.AccountId=LOCAL', 'Sum', 3600))",
     "id": "automatedBrowser",
     "label": "AutomatedBrowser",
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "WAF - Category of Bots Detected",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expression": "SUM(SEARCH('AWS/WAFV2 MetricName=(\"SampleBlockedRequest\" OR \"SampleAllowedRequest\" OR \"SampleCaptchaRequest\" OR \"SampleChallengeRequest\") BotCategory=\"bot:category:miscellaneous\" Region=\"us-west-2\" WebACL=\"friends-capstone-regional-web-acl\" :aws.AccountId=LOCAL', 'Sum', 3600))",
     "id": "miscellaneous",
     "label": "Miscellaneous",
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expression": "SUM(SEARCH('AWS/WAFV2 MetricName=(\"SampleBlockedRequest\" OR \"SampleAllowedRequest\" OR \"SampleCaptchaRequest\" OR \"SampleChallengeRequest\") BotCategory=\"bot:category:http_library\" Region=\"us-west-2\" WebACL=\"friends-capstone-regional-web-acl\" :aws.AccountId=LOCAL', 'Sum', 3600))",
     "id": "httpLibrary",
     "label": "HttpLibrary",
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expression": "SUM(SEARCH('AWS/WAFV2 MetricName=(\"SampleBlockedRequest\" OR \"SampleAllowedRequest\" OR \"SampleCaptchaRequest\" OR \"SampleChallengeRequest\") BotCategory=\"bot:category:monitoring\" Region=\"us-west-2\" WebACL=\"friends-capstone-regional-web-acl\" :aws.AccountId=LOCAL', 'Sum', 3600))",
     "id": "monitoring",
     "label": "Monitoring",
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Site Reliability Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "ALB - APIs  - Avg Response Time - Latest",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/friends-capstone-ecs-shared-alb/c1e262c436e26421"
     },
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "period": "1d",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ECS - CardCrudApis - CPU Utilization - Latest",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "friends-capstone-cluster" },
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ECS - CardCrudApis - Memory Utilization - Latest",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "friends-capstone-cluster" },
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "period": "1d",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "API Gateway - Upload Images - Latency - Latest",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "Stage": "*" },
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS - CPU Utilisation - Latest",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "friendscapstonerds" },
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "period": "1d",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ALB - APIs Avg Response Time - Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 26 },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/friends-capstone-ecs-shared-alb/c1e262c436e26421"
     },
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "period": "1d",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ECS - CardCrudApis - CPU Utilisation - Daily Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": {
      "ClusterName": "friends-capstone-cluster",
      "ServiceName": "friends-capstone-crud-api-service"
     },
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "period": "1d",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ECS - CardCrudApis - Memory Utilisation - Daily Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": {
      "ClusterName": "friends-capstone-cluster",
      "ServiceName": "friends-capstone-crud-api-service"
     },
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "period": "1d",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "API Gateway - Upload Images - Latency - Daily Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "Stage": "*" },
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "period": "1d",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS - CPU Utilisation - Daily Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 19, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "friendscapstonerds" },
     "logGroups": [
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/alb/friends-capstone-ecs-shared-alb-access-log:*",
       "name": "/alb/friends-capstone-ecs-shared-alb-access-log"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs:*",
       "name": "/aws/lambda/friends-capstone-ecs-shared-alb-forward-logs"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds:*",
       "name": "/aws/rds/instance/friendscapstonerds"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/aws/rds/instance/friendscapstonerds/error:*",
       "name": "/aws/rds/instance/friendscapstonerds/error"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/cloudtrail/friends-capstone-management-events:*",
       "name": "/cloudtrail/friends-capstone-management-events"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-cluster/friends-capstone-crud-api-service:*",
       "name": "/ecs/friends-capstone-cluster/friends-capstone-crud-api-service"
      },
      {
       "accountId": "255945442255",
       "arn": "arn:aws:logs:us-west-2:255945442255:log-group:/ecs/friends-capstone-thumbnails-api-ecs-task:*",
       "name": "/ecs/friends-capstone-thumbnails-api-ecs-task"
      }
     ],
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "period": "1d",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}