name: Auto backup of Cloudwatch dashboards

on:
  push:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  backup:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4



      - name: change permissions of script
        run: |
          sed -i -e 's/\r$//' backup.sh
          sudo chmod u+x backup.sh
          ls -la

      - run: ./backup.sh