name: Auto backup of Cloudwatch dashboards

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *" # SGT 2am / UTC 6pm
  

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: make script executable
        run: |
          sed -i -e 's/\r$//' backup.sh
          sudo chmod u+x backup.sh
          ls -la
          
      - name: backup dashboards
        run: ./backup.sh
      
      - name: list files
        run : ls ./cloudwatch/*.json

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: backup dashboards
          file_pattern: '*.json'
          repository: .
          push_options: '--force'